/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountDetails200ResponseAvatar {
    #[serde(rename = "gravatar", skip_serializing_if = "Option::is_none")]
    pub gravatar: Option<Box<models::AccountDetails200ResponseAvatarGravatar>>,
    #[serde(rename = "tmdb", skip_serializing_if = "Option::is_none")]
    pub tmdb: Option<Box<models::AccountDetails200ResponseAvatarTmdb>>,
}

impl AccountDetails200ResponseAvatar {
    pub fn new() -> AccountDetails200ResponseAvatar {
        AccountDetails200ResponseAvatar {
            gravatar: None,
            tmdb: None,
        }
    }
}

