/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountDetails200ResponseAvatarGravatar {
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
}

impl AccountDetails200ResponseAvatarGravatar {
    pub fn new() -> AccountDetails200ResponseAvatarGravatar {
        AccountDetails200ResponseAvatarGravatar {
            hash: None,
        }
    }
}

