/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountDetails200ResponseAvatarTmdb {
    #[serde(rename = "avatar_path", skip_serializing_if = "Option::is_none")]
    pub avatar_path: Option<String>,
}

impl AccountDetails200ResponseAvatarTmdb {
    pub fn new() -> AccountDetails200ResponseAvatarTmdb {
        AccountDetails200ResponseAvatarTmdb {
            avatar_path: None,
        }
    }
}

