/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationCreateGuestSession200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "guest_session_id", skip_serializing_if = "Option::is_none")]
    pub guest_session_id: Option<String>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl AuthenticationCreateGuestSession200Response {
    pub fn new() -> AuthenticationCreateGuestSession200Response {
        AuthenticationCreateGuestSession200Response {
            success: None,
            guest_session_id: None,
            expires_at: None,
        }
    }
}

