/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationCreateSessionFromLogin200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "request_token", skip_serializing_if = "Option::is_none")]
    pub request_token: Option<String>,
}

impl AuthenticationCreateSessionFromLogin200Response {
    pub fn new() -> AuthenticationCreateSessionFromLogin200Response {
        AuthenticationCreateSessionFromLogin200Response {
            success: None,
            expires_at: None,
            request_token: None,
        }
    }
}

