/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificationsTvList200ResponseCertifications {
    #[serde(rename = "AU", skip_serializing_if = "Option::is_none")]
    pub au: Option<Vec<models::CertificationsTvList200ResponseCertificationsAuInner>>,
    #[serde(rename = "BR", skip_serializing_if = "Option::is_none")]
    pub br: Option<Vec<models::CertificationsTvList200ResponseCertificationsBrInner>>,
    #[serde(rename = "CA", skip_serializing_if = "Option::is_none")]
    pub ca: Option<Vec<models::CertificationsTvList200ResponseCertificationsCaInner>>,
    #[serde(rename = "CA-QC", skip_serializing_if = "Option::is_none")]
    pub ca_qc: Option<Vec<models::CertificationsTvList200ResponseCertificationsCaQcInner>>,
    #[serde(rename = "DE", skip_serializing_if = "Option::is_none")]
    pub de: Option<Vec<models::CertificationsTvList200ResponseCertificationsDeInner>>,
    #[serde(rename = "ES", skip_serializing_if = "Option::is_none")]
    pub es: Option<Vec<models::CertificationMovieList200ResponseCertificationsCaQcInner>>,
    #[serde(rename = "FR", skip_serializing_if = "Option::is_none")]
    pub fr: Option<Vec<models::CertificationMovieList200ResponseCertificationsCaQcInner>>,
    #[serde(rename = "GB", skip_serializing_if = "Option::is_none")]
    pub gb: Option<Vec<models::CertificationsTvList200ResponseCertificationsGbInner>>,
    #[serde(rename = "HU", skip_serializing_if = "Option::is_none")]
    pub hu: Option<Vec<models::CertificationsTvList200ResponseCertificationsHuInner>>,
    #[serde(rename = "KR", skip_serializing_if = "Option::is_none")]
    pub kr: Option<Vec<models::CertificationsTvList200ResponseCertificationsKrInner>>,
    #[serde(rename = "LT", skip_serializing_if = "Option::is_none")]
    pub lt: Option<Vec<models::CertificationsTvList200ResponseCertificationsLtInner>>,
    #[serde(rename = "NL", skip_serializing_if = "Option::is_none")]
    pub nl: Option<Vec<models::CertificationMovieList200ResponseCertificationsCaQcInner>>,
    #[serde(rename = "PH", skip_serializing_if = "Option::is_none")]
    pub ph: Option<Vec<models::CertificationMovieList200ResponseCertificationsCaQcInner>>,
    #[serde(rename = "PT", skip_serializing_if = "Option::is_none")]
    pub pt: Option<Vec<models::CertificationsTvList200ResponseCertificationsPtInner>>,
    #[serde(rename = "RU", skip_serializing_if = "Option::is_none")]
    pub ru: Option<Vec<models::CertificationsTvList200ResponseCertificationsRuInner>>,
    #[serde(rename = "SK", skip_serializing_if = "Option::is_none")]
    pub sk: Option<Vec<models::CertificationMovieList200ResponseCertificationsCaQcInner>>,
    #[serde(rename = "TH", skip_serializing_if = "Option::is_none")]
    pub th: Option<Vec<models::CertificationsTvList200ResponseCertificationsThInner>>,
    #[serde(rename = "US", skip_serializing_if = "Option::is_none")]
    pub us: Option<Vec<models::CertificationsTvList200ResponseCertificationsUsInner>>,
    #[serde(rename = "IT", skip_serializing_if = "Option::is_none")]
    pub it: Option<Vec<models::CertificationsTvList200ResponseCertificationsItInner>>,
    #[serde(rename = "FI", skip_serializing_if = "Option::is_none")]
    pub fi: Option<Vec<models::CertificationsTvList200ResponseCertificationsFiInner>>,
    #[serde(rename = "MY", skip_serializing_if = "Option::is_none")]
    pub my: Option<Vec<models::CertificationsTvList200ResponseCertificationsMyInner>>,
    #[serde(rename = "NZ", skip_serializing_if = "Option::is_none")]
    pub nz: Option<Vec<models::CertificationsTvList200ResponseCertificationsNzInner>>,
    #[serde(rename = "NO", skip_serializing_if = "Option::is_none")]
    pub no: Option<Vec<models::CertificationsTvList200ResponseCertificationsNoInner>>,
    #[serde(rename = "BG", skip_serializing_if = "Option::is_none")]
    pub bg: Option<Vec<models::CertificationsTvList200ResponseCertificationsBgInner>>,
    #[serde(rename = "MX", skip_serializing_if = "Option::is_none")]
    pub mx: Option<Vec<models::CertificationsTvList200ResponseCertificationsMxInner>>,
    #[serde(rename = "IN", skip_serializing_if = "Option::is_none")]
    pub r#in: Option<Vec<models::CertificationsTvList200ResponseCertificationsInInner>>,
    #[serde(rename = "DK", skip_serializing_if = "Option::is_none")]
    pub dk: Option<Vec<models::CertificationsTvList200ResponseCertificationsDkInner>>,
    #[serde(rename = "SE", skip_serializing_if = "Option::is_none")]
    pub se: Option<Vec<models::CertificationsTvList200ResponseCertificationsSeInner>>,
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<models::CertificationsTvList200ResponseCertificationsIdInner>>,
    #[serde(rename = "TR", skip_serializing_if = "Option::is_none")]
    pub tr: Option<Vec<models::CertificationsTvList200ResponseCertificationsTrInner>>,
    #[serde(rename = "AR", skip_serializing_if = "Option::is_none")]
    pub ar: Option<Vec<models::CertificationsTvList200ResponseCertificationsArInner>>,
    #[serde(rename = "PL", skip_serializing_if = "Option::is_none")]
    pub pl: Option<Vec<models::CertificationsTvList200ResponseCertificationsPlInner>>,
    #[serde(rename = "MA", skip_serializing_if = "Option::is_none")]
    pub ma: Option<Vec<models::CertificationsTvList200ResponseCertificationsMaInner>>,
    #[serde(rename = "GR", skip_serializing_if = "Option::is_none")]
    pub gr: Option<Vec<models::CertificationsTvList200ResponseCertificationsGrInner>>,
    #[serde(rename = "IL", skip_serializing_if = "Option::is_none")]
    pub il: Option<Vec<models::CertificationsTvList200ResponseCertificationsIlInner>>,
    #[serde(rename = "TW", skip_serializing_if = "Option::is_none")]
    pub tw: Option<Vec<models::CertificationsTvList200ResponseCertificationsTwInner>>,
    #[serde(rename = "ZA", skip_serializing_if = "Option::is_none")]
    pub za: Option<Vec<models::CertificationsTvList200ResponseCertificationsZaInner>>,
    #[serde(rename = "SG", skip_serializing_if = "Option::is_none")]
    pub sg: Option<Vec<models::CertificationMovieList200ResponseCertificationsPrInner>>,
    #[serde(rename = "PR", skip_serializing_if = "Option::is_none")]
    pub pr: Option<Vec<models::CertificationsTvList200ResponseCertificationsPrInner>>,
    #[serde(rename = "VI", skip_serializing_if = "Option::is_none")]
    pub vi: Option<Vec<models::CertificationsTvList200ResponseCertificationsPrInner>>,
}

impl CertificationsTvList200ResponseCertifications {
    pub fn new() -> CertificationsTvList200ResponseCertifications {
        CertificationsTvList200ResponseCertifications {
            au: None,
            br: None,
            ca: None,
            ca_qc: None,
            de: None,
            es: None,
            fr: None,
            gb: None,
            hu: None,
            kr: None,
            lt: None,
            nl: None,
            ph: None,
            pt: None,
            ru: None,
            sk: None,
            th: None,
            us: None,
            it: None,
            fi: None,
            my: None,
            nz: None,
            no: None,
            bg: None,
            mx: None,
            r#in: None,
            dk: None,
            se: None,
            id: None,
            tr: None,
            ar: None,
            pl: None,
            ma: None,
            gr: None,
            il: None,
            tw: None,
            za: None,
            sg: None,
            pr: None,
            vi: None,
        }
    }
}

