/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionTranslations200ResponseTranslationsInnerData {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
}

impl CollectionTranslations200ResponseTranslationsInnerData {
    pub fn new() -> CollectionTranslations200ResponseTranslationsInnerData {
        CollectionTranslations200ResponseTranslationsInnerData {
            title: None,
            overview: None,
            homepage: None,
        }
    }
}

