/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionImages200Response {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "backdrops", skip_serializing_if = "Option::is_none")]
    pub backdrops: Option<Vec<models::CollectionImages200ResponseBackdropsInner>>,
    #[serde(rename = "posters", skip_serializing_if = "Option::is_none")]
    pub posters: Option<Vec<models::CollectionImages200ResponsePostersInner>>,
}

impl CollectionImages200Response {
    pub fn new() -> CollectionImages200Response {
        CollectionImages200Response {
            id: None,
            backdrops: None,
            posters: None,
        }
    }
}

