/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationDetails200Response {
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Box<models::ConfigurationDetails200ResponseImages>>,
    #[serde(rename = "change_keys", skip_serializing_if = "Option::is_none")]
    pub change_keys: Option<Vec<String>>,
}

impl ConfigurationDetails200Response {
    pub fn new() -> ConfigurationDetails200Response {
        ConfigurationDetails200Response {
            images: None,
            change_keys: None,
        }
    }
}

