/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationDetails200ResponseImages {
    #[serde(rename = "base_url", skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[serde(rename = "secure_base_url", skip_serializing_if = "Option::is_none")]
    pub secure_base_url: Option<String>,
    #[serde(rename = "backdrop_sizes", skip_serializing_if = "Option::is_none")]
    pub backdrop_sizes: Option<Vec<String>>,
    #[serde(rename = "logo_sizes", skip_serializing_if = "Option::is_none")]
    pub logo_sizes: Option<Vec<String>>,
    #[serde(rename = "poster_sizes", skip_serializing_if = "Option::is_none")]
    pub poster_sizes: Option<Vec<String>>,
    #[serde(rename = "profile_sizes", skip_serializing_if = "Option::is_none")]
    pub profile_sizes: Option<Vec<String>>,
    #[serde(rename = "still_sizes", skip_serializing_if = "Option::is_none")]
    pub still_sizes: Option<Vec<String>>,
}

impl ConfigurationDetails200ResponseImages {
    pub fn new() -> ConfigurationDetails200ResponseImages {
        ConfigurationDetails200ResponseImages {
            base_url: None,
            secure_base_url: None,
            backdrop_sizes: None,
            logo_sizes: None,
            poster_sizes: None,
            profile_sizes: None,
            still_sizes: None,
        }
    }
}

