/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenreTvList200Response {
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<models::GenreTvList200ResponseGenresInner>>,
}

impl GenreTvList200Response {
    pub fn new() -> GenreTvList200Response {
        GenreTvList200Response {
            genres: None,
        }
    }
}

