/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCheckItemStatus200Response {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "item_present", skip_serializing_if = "Option::is_none")]
    pub item_present: Option<bool>,
}

impl ListCheckItemStatus200Response {
    pub fn new() -> ListCheckItemStatus200Response {
        ListCheckItemStatus200Response {
            id: None,
            item_present: None,
        }
    }
}

