/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAddMovieRequest {
    #[serde(rename = "RAW_BODY", skip_serializing_if = "Option::is_none")]
    pub raw_body: Option<String>,
}

impl ListAddMovieRequest {
    pub fn new() -> ListAddMovieRequest {
        ListAddMovieRequest {
            raw_body: None,
        }
    }
}

