/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieChanges200ResponseChangesInnerItemsInnerValue {
    #[serde(rename = "poster", skip_serializing_if = "Option::is_none")]
    pub poster: Option<Box<models::MovieChanges200ResponseChangesInnerItemsInnerValuePoster>>,
}

impl MovieChanges200ResponseChangesInnerItemsInnerValue {
    pub fn new() -> MovieChanges200ResponseChangesInnerItemsInnerValue {
        MovieChanges200ResponseChangesInnerItemsInnerValue {
            poster: None,
        }
    }
}

