/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieAlternativeTitles200ResponseTitlesInner {
    #[serde(rename = "iso_3166_1", skip_serializing_if = "Option::is_none")]
    pub iso_3166_1: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl MovieAlternativeTitles200ResponseTitlesInner {
    pub fn new() -> MovieAlternativeTitles200ResponseTitlesInner {
        MovieAlternativeTitles200ResponseTitlesInner {
            iso_3166_1: None,
            title: None,
            r#type: None,
        }
    }
}

