/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieImages200Response {
    #[serde(rename = "backdrops", skip_serializing_if = "Option::is_none")]
    pub backdrops: Option<Vec<models::MovieImages200ResponseBackdropsInner>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "logos", skip_serializing_if = "Option::is_none")]
    pub logos: Option<Vec<models::MovieImages200ResponseLogosInner>>,
    #[serde(rename = "posters", skip_serializing_if = "Option::is_none")]
    pub posters: Option<Vec<models::MovieImages200ResponsePostersInner>>,
}

impl MovieImages200Response {
    pub fn new() -> MovieImages200Response {
        MovieImages200Response {
            backdrops: None,
            id: None,
            logos: None,
            posters: None,
        }
    }
}

