/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieAlternativeTitles200Response {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "titles", skip_serializing_if = "Option::is_none")]
    pub titles: Option<Vec<models::MovieAlternativeTitles200ResponseTitlesInner>>,
}

impl MovieAlternativeTitles200Response {
    pub fn new() -> MovieAlternativeTitles200Response {
        MovieAlternativeTitles200Response {
            id: None,
            titles: None,
        }
    }
}

