/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieNowPlayingList200ResponseDates {
    #[serde(rename = "maximum", skip_serializing_if = "Option::is_none")]
    pub maximum: Option<String>,
    #[serde(rename = "minimum", skip_serializing_if = "Option::is_none")]
    pub minimum: Option<String>,
}

impl MovieNowPlayingList200ResponseDates {
    pub fn new() -> MovieNowPlayingList200ResponseDates {
        MovieNowPlayingList200ResponseDates {
            maximum: None,
            minimum: None,
        }
    }
}

