/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieAccountStates200Response {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "favorite", skip_serializing_if = "Option::is_none")]
    pub favorite: Option<bool>,
    #[serde(rename = "rated", skip_serializing_if = "Option::is_none")]
    pub rated: Option<Box<models::MovieAccountStates200ResponseRated>>,
    #[serde(rename = "watchlist", skip_serializing_if = "Option::is_none")]
    pub watchlist: Option<bool>,
}

impl MovieAccountStates200Response {
    pub fn new() -> MovieAccountStates200Response {
        MovieAccountStates200Response {
            id: None,
            favorite: None,
            rated: None,
            watchlist: None,
        }
    }
}

