/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieCredits200Response {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "cast", skip_serializing_if = "Option::is_none")]
    pub cast: Option<Vec<models::MovieCredits200ResponseCastInner>>,
    #[serde(rename = "crew", skip_serializing_if = "Option::is_none")]
    pub crew: Option<Vec<models::MovieCredits200ResponseCrewInner>>,
}

impl MovieCredits200Response {
    pub fn new() -> MovieCredits200Response {
        MovieCredits200Response {
            id: None,
            cast: None,
            crew: None,
        }
    }
}

