/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieImages200ResponseBackdropsInner {
    #[serde(rename = "aspect_ratio", skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<f64>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "iso_639_1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso_639_1: Option<Option<serde_json::Value>>,
    #[serde(rename = "file_path", skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
    #[serde(rename = "vote_average", skip_serializing_if = "Option::is_none")]
    pub vote_average: Option<f64>,
    #[serde(rename = "vote_count", skip_serializing_if = "Option::is_none")]
    pub vote_count: Option<i32>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl MovieImages200ResponseBackdropsInner {
    pub fn new() -> MovieImages200ResponseBackdropsInner {
        MovieImages200ResponseBackdropsInner {
            aspect_ratio: None,
            height: None,
            iso_639_1: None,
            file_path: None,
            vote_average: None,
            vote_count: None,
            width: None,
        }
    }
}

