/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieAddRatingRequest {
    #[serde(rename = "RAW_BODY")]
    pub raw_body: String,
}

impl MovieAddRatingRequest {
    pub fn new(raw_body: String) -> MovieAddRatingRequest {
        MovieAddRatingRequest {
            raw_body,
        }
    }
}

