/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonChanges200ResponseChangesInner {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::PersonChanges200ResponseChangesInnerItemsInner>>,
}

impl PersonChanges200ResponseChangesInner {
    pub fn new() -> PersonChanges200ResponseChangesInner {
        PersonChanges200ResponseChangesInner {
            key: None,
            items: None,
        }
    }
}

