/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonExternalIds200Response {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "freebase_mid", skip_serializing_if = "Option::is_none")]
    pub freebase_mid: Option<String>,
    #[serde(rename = "freebase_id", skip_serializing_if = "Option::is_none")]
    pub freebase_id: Option<String>,
    #[serde(rename = "imdb_id", skip_serializing_if = "Option::is_none")]
    pub imdb_id: Option<String>,
    #[serde(rename = "tvrage_id", skip_serializing_if = "Option::is_none")]
    pub tvrage_id: Option<i32>,
    #[serde(rename = "wikidata_id", skip_serializing_if = "Option::is_none")]
    pub wikidata_id: Option<String>,
    #[serde(rename = "facebook_id", skip_serializing_if = "Option::is_none")]
    pub facebook_id: Option<String>,
    #[serde(rename = "instagram_id", skip_serializing_if = "Option::is_none")]
    pub instagram_id: Option<String>,
    #[serde(rename = "tiktok_id", skip_serializing_if = "Option::is_none")]
    pub tiktok_id: Option<String>,
    #[serde(rename = "twitter_id", skip_serializing_if = "Option::is_none")]
    pub twitter_id: Option<String>,
    #[serde(rename = "youtube_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub youtube_id: Option<Option<serde_json::Value>>,
}

impl PersonExternalIds200Response {
    pub fn new() -> PersonExternalIds200Response {
        PersonExternalIds200Response {
            id: None,
            freebase_mid: None,
            freebase_id: None,
            imdb_id: None,
            tvrage_id: None,
            wikidata_id: None,
            facebook_id: None,
            instagram_id: None,
            tiktok_id: None,
            twitter_id: None,
            youtube_id: None,
        }
    }
}

