/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonLatestId200Response {
    #[serde(rename = "adult", skip_serializing_if = "Option::is_none")]
    pub adult: Option<bool>,
    #[serde(rename = "also_known_as", skip_serializing_if = "Option::is_none")]
    pub also_known_as: Option<Vec<serde_json::Value>>,
    #[serde(rename = "biography", skip_serializing_if = "Option::is_none")]
    pub biography: Option<String>,
    #[serde(rename = "birthday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub birthday: Option<Option<serde_json::Value>>,
    #[serde(rename = "deathday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deathday: Option<Option<serde_json::Value>>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<i32>,
    #[serde(rename = "homepage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<Option<serde_json::Value>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "imdb_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub imdb_id: Option<Option<serde_json::Value>>,
    #[serde(rename = "known_for_department", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub known_for_department: Option<Option<serde_json::Value>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "place_of_birth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub place_of_birth: Option<Option<serde_json::Value>>,
    #[serde(rename = "popularity", skip_serializing_if = "Option::is_none")]
    pub popularity: Option<i32>,
    #[serde(rename = "profile_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub profile_path: Option<Option<serde_json::Value>>,
}

impl PersonLatestId200Response {
    pub fn new() -> PersonLatestId200Response {
        PersonLatestId200Response {
            adult: None,
            also_known_as: None,
            biography: None,
            birthday: None,
            deathday: None,
            gender: None,
            homepage: None,
            id: None,
            imdb_id: None,
            known_for_department: None,
            name: None,
            place_of_birth: None,
            popularity: None,
            profile_path: None,
        }
    }
}

