/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewDetails200ResponseAuthorDetails {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "avatar_path", skip_serializing_if = "Option::is_none")]
    pub avatar_path: Option<String>,
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<i32>,
}

impl ReviewDetails200ResponseAuthorDetails {
    pub fn new() -> ReviewDetails200ResponseAuthorDetails {
        ReviewDetails200ResponseAuthorDetails {
            name: None,
            username: None,
            avatar_path: None,
            rating: None,
        }
    }
}

