/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvEpisodeDetails200Response {
    #[serde(rename = "air_date", skip_serializing_if = "Option::is_none")]
    pub air_date: Option<String>,
    #[serde(rename = "crew", skip_serializing_if = "Option::is_none")]
    pub crew: Option<Vec<models::TvEpisodeDetails200ResponseCrewInner>>,
    #[serde(rename = "episode_number", skip_serializing_if = "Option::is_none")]
    pub episode_number: Option<i32>,
    #[serde(rename = "guest_stars", skip_serializing_if = "Option::is_none")]
    pub guest_stars: Option<Vec<models::TvEpisodeDetails200ResponseGuestStarsInner>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "production_code", skip_serializing_if = "Option::is_none")]
    pub production_code: Option<String>,
    #[serde(rename = "runtime", skip_serializing_if = "Option::is_none")]
    pub runtime: Option<i32>,
    #[serde(rename = "season_number", skip_serializing_if = "Option::is_none")]
    pub season_number: Option<i32>,
    #[serde(rename = "still_path", skip_serializing_if = "Option::is_none")]
    pub still_path: Option<String>,
    #[serde(rename = "vote_average", skip_serializing_if = "Option::is_none")]
    pub vote_average: Option<f64>,
    #[serde(rename = "vote_count", skip_serializing_if = "Option::is_none")]
    pub vote_count: Option<i32>,
}

impl TvEpisodeDetails200Response {
    pub fn new() -> TvEpisodeDetails200Response {
        TvEpisodeDetails200Response {
            air_date: None,
            crew: None,
            episode_number: None,
            guest_stars: None,
            name: None,
            overview: None,
            id: None,
            production_code: None,
            runtime: None,
            season_number: None,
            still_path: None,
            vote_average: None,
            vote_count: None,
        }
    }
}

