/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeriesDetails200ResponseProductionCountriesInner {
    #[serde(rename = "iso_3166_1", skip_serializing_if = "Option::is_none")]
    pub iso_3166_1: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl TvSeriesDetails200ResponseProductionCountriesInner {
    pub fn new() -> TvSeriesDetails200ResponseProductionCountriesInner {
        TvSeriesDetails200ResponseProductionCountriesInner {
            iso_3166_1: None,
            name: None,
        }
    }
}

