/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    #[serde(rename = "credit_id", skip_serializing_if = "Option::is_none")]
    pub credit_id: Option<String>,
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<String>,
    #[serde(rename = "episode_count", skip_serializing_if = "Option::is_none")]
    pub episode_count: Option<i32>,
}

impl TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    pub fn new() -> TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
        TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
            credit_id: None,
            job: None,
            episode_count: None,
        }
    }
}

