/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeriesChanges200ResponseChangesInnerItemsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "iso_639_1", skip_serializing_if = "Option::is_none")]
    pub iso_639_1: Option<String>,
    #[serde(rename = "iso_3166_1", skip_serializing_if = "Option::is_none")]
    pub iso_3166_1: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<models::TvSeriesChanges200ResponseChangesInnerItemsInnerValue>>,
    #[serde(rename = "original_value", skip_serializing_if = "Option::is_none")]
    pub original_value: Option<Box<models::TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue>>,
}

impl TvSeriesChanges200ResponseChangesInnerItemsInner {
    pub fn new() -> TvSeriesChanges200ResponseChangesInnerItemsInner {
        TvSeriesChanges200ResponseChangesInnerItemsInner {
            id: None,
            action: None,
            time: None,
            iso_639_1: None,
            iso_3166_1: None,
            value: None,
            original_value: None,
        }
    }
}

