/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeasonChangesById200Response {
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<models::TvSeasonChangesById200ResponseChangesInner>>,
}

impl TvSeasonChangesById200Response {
    pub fn new() -> TvSeasonChangesById200Response {
        TvSeasonChangesById200Response {
            changes: None,
        }
    }
}

