/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeriesLatestId200ResponseSeasonsInner {
    #[serde(rename = "air_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub air_date: Option<Option<serde_json::Value>>,
    #[serde(rename = "episode_count", skip_serializing_if = "Option::is_none")]
    pub episode_count: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(rename = "poster_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub poster_path: Option<Option<serde_json::Value>>,
    #[serde(rename = "season_number", skip_serializing_if = "Option::is_none")]
    pub season_number: Option<i32>,
}

impl TvSeriesLatestId200ResponseSeasonsInner {
    pub fn new() -> TvSeriesLatestId200ResponseSeasonsInner {
        TvSeriesLatestId200ResponseSeasonsInner {
            air_date: None,
            episode_count: None,
            id: None,
            name: None,
            overview: None,
            poster_path: None,
            season_number: None,
        }
    }
}

