/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeasonTranslations200ResponseTranslationsInnerData {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
}

impl TvSeasonTranslations200ResponseTranslationsInnerData {
    pub fn new() -> TvSeasonTranslations200ResponseTranslationsInnerData {
        TvSeasonTranslations200ResponseTranslationsInnerData {
            name: None,
            overview: None,
        }
    }
}

