/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeasonAggregateCredits200ResponseCrewInner {
    #[serde(rename = "adult", skip_serializing_if = "Option::is_none")]
    pub adult: Option<bool>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "known_for_department", skip_serializing_if = "Option::is_none")]
    pub known_for_department: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "original_name", skip_serializing_if = "Option::is_none")]
    pub original_name: Option<String>,
    #[serde(rename = "popularity", skip_serializing_if = "Option::is_none")]
    pub popularity: Option<f64>,
    #[serde(rename = "profile_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub profile_path: Option<Option<serde_json::Value>>,
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<models::TvSeasonAggregateCredits200ResponseCrewInnerJobsInner>>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "total_episode_count", skip_serializing_if = "Option::is_none")]
    pub total_episode_count: Option<i32>,
}

impl TvSeasonAggregateCredits200ResponseCrewInner {
    pub fn new() -> TvSeasonAggregateCredits200ResponseCrewInner {
        TvSeasonAggregateCredits200ResponseCrewInner {
            adult: None,
            gender: None,
            id: None,
            known_for_department: None,
            name: None,
            original_name: None,
            popularity: None,
            profile_path: None,
            jobs: None,
            department: None,
            total_episode_count: None,
        }
    }
}

