/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeriesLatestId200ResponseLastEpisodeToAir {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
    #[serde(rename = "vote_average", skip_serializing_if = "Option::is_none")]
    pub vote_average: Option<i32>,
    #[serde(rename = "vote_count", skip_serializing_if = "Option::is_none")]
    pub vote_count: Option<i32>,
    #[serde(rename = "air_date", skip_serializing_if = "Option::is_none")]
    pub air_date: Option<String>,
    #[serde(rename = "episode_number", skip_serializing_if = "Option::is_none")]
    pub episode_number: Option<i32>,
    #[serde(rename = "production_code", skip_serializing_if = "Option::is_none")]
    pub production_code: Option<String>,
    #[serde(rename = "runtime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub runtime: Option<Option<serde_json::Value>>,
    #[serde(rename = "season_number", skip_serializing_if = "Option::is_none")]
    pub season_number: Option<i32>,
    #[serde(rename = "show_id", skip_serializing_if = "Option::is_none")]
    pub show_id: Option<i32>,
    #[serde(rename = "still_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub still_path: Option<Option<serde_json::Value>>,
}

impl TvSeriesLatestId200ResponseLastEpisodeToAir {
    pub fn new() -> TvSeriesLatestId200ResponseLastEpisodeToAir {
        TvSeriesLatestId200ResponseLastEpisodeToAir {
            id: None,
            name: None,
            overview: None,
            vote_average: None,
            vote_count: None,
            air_date: None,
            episode_number: None,
            production_code: None,
            runtime: None,
            season_number: None,
            show_id: None,
            still_path: None,
        }
    }
}

