/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
    #[serde(rename = "file_path", skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
    #[serde(rename = "iso_639_1", skip_serializing_if = "Option::is_none")]
    pub iso_639_1: Option<String>,
}

impl TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
    pub fn new() -> TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
        TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValuePoster {
            file_path: None,
            iso_639_1: None,
        }
    }
}

