/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeasonChangesById200ResponseChangesInnerItemsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<models::TvSeasonChangesById200ResponseChangesInnerItemsInnerValue>>,
}

impl TvSeasonChangesById200ResponseChangesInnerItemsInner {
    pub fn new() -> TvSeasonChangesById200ResponseChangesInnerItemsInner {
        TvSeasonChangesById200ResponseChangesInnerItemsInner {
            id: None,
            action: None,
            time: None,
            value: None,
        }
    }
}

