/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    #[serde(rename = "episode_id", skip_serializing_if = "Option::is_none")]
    pub episode_id: Option<i32>,
    #[serde(rename = "episode_number", skip_serializing_if = "Option::is_none")]
    pub episode_number: Option<i32>,
}

impl TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
    pub fn new() -> TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
        TvSeasonChangesById200ResponseChangesInnerItemsInnerValue {
            episode_id: None,
            episode_number: None,
        }
    }
}

