/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvSeasonAggregateCredits200ResponseCastInnerRolesInner {
    #[serde(rename = "credit_id", skip_serializing_if = "Option::is_none")]
    pub credit_id: Option<String>,
    #[serde(rename = "character", skip_serializing_if = "Option::is_none")]
    pub character: Option<String>,
    #[serde(rename = "episode_count", skip_serializing_if = "Option::is_none")]
    pub episode_count: Option<i32>,
}

impl TvSeasonAggregateCredits200ResponseCastInnerRolesInner {
    pub fn new() -> TvSeasonAggregateCredits200ResponseCastInnerRolesInner {
        TvSeasonAggregateCredits200ResponseCastInnerRolesInner {
            credit_id: None,
            character: None,
            episode_count: None,
        }
    }
}

