/*
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchProvidersMovieList200Response {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::WatchProvidersMovieList200ResponseResultsInner>>,
}

impl WatchProvidersMovieList200Response {
    pub fn new() -> WatchProvidersMovieList200Response {
        WatchProvidersMovieList200Response {
            results: None,
        }
    }
}

